# Generated by Django 3.1.4 on 2021-05-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('column_separator', models.CharField(choices=[('comma', 'Comma (,)'), ('semicolon', 'Semicolon (;)'), ('tab', 'Tab (\\t)'), ('space', 'Space ( )'), ('pipe', 'Pipe (|)')], max_length=10)),
                ('string_character', models.PositiveIntegerField(choices=[(1, "Single quote (')"), (2, 'Double quote(")')])),
                ('modified_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain', 'Domain name'), ('phone', 'Phone number'), ('company', 'Company name'), ('text', 'Text')], max_length=20)),
                ('range_to', models.IntegerField(null=True, verbose_name='To')),
                ('range_from', models.IntegerField(null=True, verbose_name='From')),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
